// Topic deck: Business / Office
// ~135 cards. Practical professional vocabulary for work contexts.

interface SeedCard {
  id: string;
  word: string;
  translation: string;
  pos: string;
  level: string;
  gender?: 'm' | 'f' | 'n';
  example: string;
  exampleEn: string;
}

const make = (w: string, t: string, p: string, lvl: string, gender?: string): SeedCard => ({
  id: 'biz-' + w.toLowerCase().replace(/[^a-zäöüß]/g, ''),
  word: w,
  translation: t,
  pos: p,
  level: lvl,
  ...(gender ? { gender: gender as 'm' | 'f' | 'n' } : {}),
  example: '',
  exampleEn: '',
});

export const TOPIC_BUSINESS: SeedCard[] = [
  // Office / work environment
  make('das Büro', 'office', 'noun', 'B1', 'n'),
  make('der Schreibtisch', 'desk', 'noun', 'A2', 'm'),
  make('der Stuhl', 'chair', 'noun', 'A1', 'm'),
  make('der Computer', 'computer', 'noun', 'A2', 'm'),
  make('der Bildschirm', 'screen', 'noun', 'B1', 'm'),
  make('die Tastatur', 'keyboard', 'noun', 'B1', 'f'),
  make('die Maus', 'mouse (computer)', 'noun', 'B1', 'f'),
  make('der Drucker', 'printer', 'noun', 'B2', 'm'),
  make('das Dokument', 'document', 'noun', 'B1', 'n'),
  make('die Akte', 'file/folder', 'noun', 'B2', 'f'),
  make('der Ordner', 'folder', 'noun', 'B2', 'm'),
  make('der Kalender', 'calendar', 'noun', 'A2', 'm'),
  make('der Terminkalender', 'appointment calendar', 'noun', 'B2', 'm'),
  make('das Whiteboard', 'whiteboard', 'noun', 'B2', 'n'),
  make('der Beamer', 'projector', 'noun', 'B2', 'm'),
  make('die Besprechung', 'meeting', 'noun', 'B1', 'f'),
  make('das Meeting', 'meeting', 'noun', 'B1', 'n'),
  make('die Konferenz', 'conference', 'noun', 'B1', 'f'),
  make('das Telefon', 'telephone', 'noun', 'A2', 'n'),
  make('der Anruf', 'phone call', 'noun', 'B1', 'm'),
  make('die E-Mail', 'email', 'noun', 'A2', 'f'),
  make('die Nachricht', 'message', 'noun', 'A2', 'f'),
  make('der Brief', 'letter', 'noun', 'A2', 'm'),
  // Roles
  make('der Chef', 'boss', 'noun', 'A2', 'm'),
  make('die Chefin', 'boss (f)', 'noun', 'B1', 'f'),
  make('der Kollege', 'colleague (m)', 'noun', 'B1', 'm'),
  make('die Kollegin', 'colleague (f)', 'noun', 'B1', 'f'),
  make('der Mitarbeiter', 'employee (m)', 'noun', 'B1', 'm'),
  make('die Mitarbeiterin', 'employee (f)', 'noun', 'B1', 'f'),
  make('der Kunde', 'customer (m)', 'noun', 'B1', 'm'),
  make('die Kundin', 'customer (f)', 'noun', 'B1', 'f'),
  make('der Kunden', 'customers (pl)', 'noun', 'B1', 'm'),
  make('der Lieferant', 'supplier', 'noun', 'B2', 'm'),
  make('der Geschäftspartner', 'business partner', 'noun', 'B2', 'm'),
  make('die Abteilung', 'department', 'noun', 'B1', 'f'),
  make('die Firma', 'company', 'noun', 'A2', 'f'),
  make('das Unternehmen', 'enterprise/company', 'noun', 'B1', 'n'),
  make('der Konzern', 'corporation', 'noun', 'B2', 'm'),
  // Actions
  make('arbeiten', 'to work', 'verb', 'A1'),
  make('anrufen', 'to call', 'verb', 'A2'),
  make('schreiben', 'to write', 'verb', 'A1'),
  make('lesen', 'to read', 'verb', 'A1'),
  make('senden', 'to send', 'verb', 'B1'),
  make('empfangen', 'to receive', 'verb', 'B1'),
  make('beantworten', 'to answer (reply)', 'verb', 'B1'),
  make('unterschreiben', 'to sign', 'verb', 'B2'),
  make('genehmigen', 'to approve', 'verb', 'B2'),
  make('planen', 'to plan', 'verb', 'A2'),
  make('organisieren', 'to organize', 'verb', 'B1'),
  make('koordinieren', 'to coordinate', 'verb', 'B2'),
  make('vorbereiten', 'to prepare', 'verb', 'B1'),
  make('präsentieren', 'to present', 'verb', 'B1'),
  make('verhandeln', 'to negotiate', 'verb', 'B2'),
  make('überzeugen', 'to convince', 'verb', 'B2'),
  make('übernehmen', 'to take over', 'verb', 'B2'),
  make('verantworten', 'to be responsible for', 'verb', 'B2'),
  make('befördern', 'to promote', 'verb', 'B2'),
  make('einstellen', 'to hire', 'verb', 'B2'),
  make('kündigen', 'to resign / cancel', 'verb', 'B2'),
  make('zusammenarbeiten', 'to collaborate', 'verb', 'B2'),
  // Email / correspondence phrases
  make('Sehr geehrte Frau', 'Dear Ms. (formal)', 'noun', 'B2', 'f'),
  make('Sehr geehrter Herr', 'Dear Mr. (formal)', 'noun', 'B2', 'm'),
  make('Mit freundlichen Grüßen', 'Sincerely', 'interj', 'B1'),
  make('die Anfrage', 'inquiry', 'noun', 'B1', 'f'),
  make('das Angebot', 'offer', 'noun', 'B1', 'n'),
  make('die Bestellung', 'order', 'noun', 'B1', 'f'),
  make('die Rechnung', 'invoice', 'noun', 'B1', 'f'),
  make('die Quittung', 'receipt', 'noun', 'B1', 'f'),
  make('die Mahnung', 'dunning notice', 'noun', 'B2', 'f'),
  make('die Zahlung', 'payment', 'noun', 'B1', 'f'),
  make('die Überweisung', 'transfer', 'noun', 'B1', 'f'),
  make('der Betrag', 'amount', 'noun', 'B1', 'm'),
  make('die Summe', 'sum', 'noun', 'B1', 'f'),
  make('die Steuer', 'tax', 'noun', 'B1', 'f'),
  make('die Mehrwertsteuer', 'VAT', 'noun', 'B2', 'f'),
  make('die Lohnsteuer', 'income tax', 'noun', 'B2', 'f'),
  // Meetings + projects
  make('der Termin', 'appointment', 'noun', 'B1', 'm'),
  make('der Zeitplan', 'schedule', 'noun', 'B1', 'm'),
  make('der Arbeitsplan', 'work plan', 'noun', 'B2', 'm'),
  make('das Projekt', 'project', 'noun', 'A2', 'n'),
  make('die Aufgabe', 'task', 'noun', 'B1', 'f'),
  make('das Ziel', 'goal', 'noun', 'A2', 'n'),
  make('die Deadline', 'deadline', 'noun', 'B1', 'f'),
  make('der Bericht', 'report', 'noun', 'B1', 'm'),
  make('das Protokoll', 'minutes/protocol', 'noun', 'B2', 'n'),
  make('die Tagesordnung', 'agenda', 'noun', 'B2', 'f'),
  make('die Präsentation', 'presentation', 'noun', 'B1', 'f'),
  make('der Vortrag', 'talk/lecture', 'noun', 'B1', 'm'),
  make('die Diskussion', 'discussion', 'noun', 'B1', 'f'),
  make('die Entscheidung', 'decision', 'noun', 'B1', 'f'),
  make('der Vorschlag', 'proposal', 'noun', 'B1', 'm'),
  // Common phrases
  make('vereinbaren', 'to arrange/agree', 'verb', 'B1'),
  make('bestätigen', 'to confirm', 'verb', 'B1'),
  make('verschieben', 'to postpone', 'verb', 'B2'),
  make('absagen', 'to cancel', 'verb', 'B1'),
  make('zustimmen', 'to agree', 'verb', 'B1'),
  make('ablehnen', 'to decline', 'verb', 'B2'),
  make('sich beschweren', 'to complain', 'verb', 'B2'),
  make('sich entschuldigen', 'to apologize', 'verb', 'B2'),
  make('sich bedanken', 'to thank', 'verb', 'B2'),
  make('erinnern an', 'to remind of', 'verb', 'B2'),
  make('hinweisen auf', 'to point out', 'verb', 'B2'),
  // Job titles (common)
  make('der Manager', 'manager', 'noun', 'B1', 'm'),
  make('die Managerin', 'manager (f)', 'noun', 'B1', 'f'),
  make('der Direktor', 'director', 'noun', 'B2', 'm'),
  make('die Direktorin', 'director (f)', 'noun', 'B2', 'f'),
  make('der Geschäftsführer', 'CEO/managing director', 'noun', 'B2', 'm'),
  make('der Vorstand', 'board/executive', 'noun', 'B2', 'm'),
  make('der Angestellte', 'employee (formal)', 'noun', 'B2', 'm'),
  make('der Auszubildende', 'trainee', 'noun', 'B2', 'm'),
  make('der Praktikant', 'intern', 'noun', 'B2', 'm'),
  make('der Freiberufler', 'freelancer', 'noun', 'B2', 'm'),
  // Career vocabulary
  make('die Karriere', 'career', 'noun', 'B2', 'f'),
  make('die Erfahrung', 'experience', 'noun', 'B1', 'f'),
  make('die Qualifikation', 'qualification', 'noun', 'B2', 'f'),
  make('die Fähigkeit', 'ability/skill', 'noun', 'B2', 'f'),
  make('die Kenntnisse', 'knowledge/skills (pl)', 'noun', 'B2', 'f'),
  make('das Gehalt', 'salary', 'noun', 'B1', 'n'),
  make('der Lohn', 'wage', 'noun', 'B2', 'm'),
  make('die Beförderung', 'promotion', 'noun', 'B2', 'f'),
  make('die Kündigung', 'dismissal/notice', 'noun', 'B2', 'f'),
  make('die Stelle', 'position', 'noun', 'B1', 'f'),
  make('die Stellenausschreibung', 'job ad', 'noun', 'B2', 'f'),
  make('die Bewerbung', 'application', 'noun', 'B1', 'f'),
  make('der Lebenslauf', 'CV/resume', 'noun', 'B1', 'm'),
  make('das Anschreiben', 'cover letter', 'noun', 'B2', 'n'),
  make('das Vorstellungsgespräch', 'job interview', 'noun', 'B1', 'n'),
];