// Topic deck: Business / Office
// ~135 cards. Practical professional vocabulary for work contexts.

interface SeedCard {
  id: string;
  word: string;
  translation: string;
  pos: string;
  level: string;
  gender?: 'm' | 'f' | 'n';
  example: string;
  exampleEn: string;
}

const make = (w: string, t: string, p: string, lvl: string, gender?: string, example?: string, exampleEn?: string): SeedCard => ({
  id: 'biz-' + w.toLowerCase().replace(/[^a-zäöüß]/g, ''),
  word: w,
  translation: t,
  pos: p,
  level: lvl,
  ...(gender ? { gender: gender as 'm' | 'f' | 'n' } : {}),
  example: example || '',
  exampleEn: exampleEn || '',
});

export const TOPIC_BUSINESS: SeedCard[] = [
  // Office / work environment
  make('das Büro', 'office', 'noun', 'B1', 'n', 'Ich gehe ins Büro.', 'I am going to the office.'),
  make('der Schreibtisch', 'desk', 'noun', 'A2', 'm', 'Der Vertrag liegt auf dem Schreibtisch.', 'The contract is lying on the desk.'),
  make('der Stuhl', 'chair', 'noun', 'A1', 'm', 'Setz dich auf den Stuhl.', 'Sit down on the chair.'),
  make('der Computer', 'computer', 'noun', 'A2', 'm', 'Mein Computer ist sehr schnell.', 'My computer is very fast.'),
  make('der Bildschirm', 'screen', 'noun', 'B1', 'm', 'Der Bildschirm ist 27 Zoll groß.', 'The screen is 27 inches.'),
  make('die Tastatur', 'keyboard', 'noun', 'B1', 'f', 'Die Tastatur ist kaputt.', 'The keyboard is broken.'),
  make('die Maus', 'mouse (computer)', 'noun', 'B1', 'f', 'Die Maus funktioniert nicht.', 'The mouse is not working.'),
  make('der Drucker', 'printer', 'noun', 'B2', 'm', 'Der Drucker braucht neues Papier.', 'The printer needs new paper.'),
  make('das Dokument', 'document', 'noun', 'B1', 'n', 'Bitte drucke das Dokument.', 'Please print the document.'),
  make('die Akte', 'file/folder', 'noun', 'B2', 'f', 'Ich öffne die Akte.', 'I open the file.'),
  make('der Ordner', 'folder', 'noun', 'B2', 'm', 'Der Ordner ist auf dem Schreibtisch.', 'The folder is on the desk.'),
  make('der Kalender', 'calendar', 'noun', 'A2', 'm', 'Der Termin steht im Kalender.', 'The appointment is in the calendar.'),
  make('der Terminkalender', 'appointment calendar', 'noun', 'B2', 'm', 'Schau in den Terminkalender.', 'Check the appointment calendar.'),
  make('das Whiteboard', 'whiteboard', 'noun', 'B2', 'n', 'Schreib es auf das Whiteboard.', 'Write it on the whiteboard.'),
  make('der Beamer', 'projector', 'noun', 'B2', 'm', 'Der Beamer funktioniert nicht.', 'The projector is not working.'),
  make('die Besprechung', 'meeting', 'noun', 'B1', 'f', 'Die Besprechung beginnt um 10 Uhr.', 'The meeting starts at 10 AM.'),
  make('das Meeting', 'meeting', 'noun', 'B1', 'n', 'Das Meeting dauert eine Stunde.', 'The meeting lasts one hour.'),
  make('die Konferenz', 'conference', 'noun', 'B1', 'f', 'Die Konferenz ist in Berlin.', 'The conference is in Berlin.'),
  make('das Telefon', 'telephone', 'noun', 'A2', 'n', 'Das Telefon klingelt.', 'The phone is ringing.'),
  make('der Anruf', 'phone call', 'noun', 'B1', 'm', 'Ich erwarte einen wichtigen Anruf.', 'I am expecting an important call.'),
  make('die E-Mail', 'email', 'noun', 'A2', 'f', 'Ich schreibe dir eine E-Mail.', 'I am writing you an email.'),
  make('die Nachricht', 'message', 'noun', 'A2', 'f', 'Hast du meine Nachricht bekommen?', 'Did you get my message?'),
  make('der Brief', 'letter', 'noun', 'A2', 'm', 'Der Brief ist heute angekommen.', 'The letter arrived today.'),
  // Roles
  make('der Chef', 'boss', 'noun', 'A2', 'm', 'Mein Chef ist im Urlaub.', 'My boss is on vacation.'),
  make('die Chefin', 'boss (f)', 'noun', 'B1', 'f', 'Meine Chefin hat heute frei.', 'My boss (female) is off today.'),
  make('der Kollege', 'colleague (m)', 'noun', 'B1', 'm', 'Mein Kollege hilft mir.', 'My colleague is helping me.'),
  make('die Kollegin', 'colleague (f)', 'noun', 'B1', 'f', 'Meine Kollegin arbeitet remote.', 'My colleague (female) works remote.'),
  make('der Mitarbeiter', 'employee (m)', 'noun', 'B1', 'm', 'Der Mitarbeiter ist neu.', 'The employee is new.'),
  make('die Mitarbeiterin', 'employee (f)', 'noun', 'B1', 'f', 'Die Mitarbeiterin spricht drei Sprachen.', 'The employee (female) speaks three languages.'),
  make('der Kunde', 'customer (m)', 'noun', 'B1', 'm', 'Der Kunde wartet schon.', 'The customer is already waiting.'),
  make('die Kundin', 'customer (f)', 'noun', 'B1', 'f', 'Die Kundin hat eine Frage.', 'The customer (female) has a question.'),
  make('der Kunden', 'customers (pl)', 'noun', 'B1', 'm', 'Die Kunden kommen heute.', 'The customers are coming today.'),
  make('der Lieferant', 'supplier', 'noun', 'B2', 'm', 'Der Lieferant verspätet sich.', 'The supplier is late.'),
  make('der Geschäftspartner', 'business partner', 'noun', 'B2', 'm', 'Unser Geschäftspartner kommt morgen.', 'Our business partner is coming tomorrow.'),
  make('die Abteilung', 'department', 'noun', 'B1', 'f', 'Die Marketing-Abteilung ist im 3. Stock.', 'The marketing department is on the 3rd floor.'),
  make('die Firma', 'company', 'noun', 'A2', 'f', 'Die Firma hat 50 Mitarbeiter.', 'The company has 50 employees.'),
  make('das Unternehmen', 'enterprise/company', 'noun', 'B1', 'n', 'Das Unternehmen wächst schnell.', 'The company is growing fast.'),
  make('der Konzern', 'corporation', 'noun', 'B2', 'm', 'Der Konzern hat viele Tochterfirmen.', 'The corporation has many subsidiaries.'),
  // Actions
  make('arbeiten', 'to work', 'verb', 'A1', 'Ich arbeite von zu Hause.', 'I work from home.'),
  make('anrufen', 'to call', 'verb', 'A2', 'Bitte ruf mich morgen an.', 'Please call me tomorrow.'),
  make('schreiben', 'to write', 'verb', 'A1', 'Ich schreibe einen Bericht.', 'I am writing a report.'),
  make('lesen', 'to read', 'verb', 'A1', 'Ich lese die E-Mail.', 'I am reading the email.'),
  make('senden', 'to send', 'verb', 'B1', 'Ich sende das Dokument jetzt.', 'I am sending the document now.'),
  make('empfangen', 'to receive', 'verb', 'B1', 'Ich habe deine Nachricht empfangen.', 'I received your message.'),
  make('beantworten', 'to answer (reply)', 'verb', 'B1', 'Bitte beantworte meine Frage.', 'Please answer my question.'),
  make('unterschreiben', 'to sign', 'verb', 'B2', 'Bitte unterschreibe hier.', 'Please sign here.'),
  make('genehmigen', 'to approve', 'verb', 'B2', 'Der Chef muss den Antrag genehmigen.', 'The boss must approve the request.'),
  make('planen', 'to plan', 'verb', 'A2', 'Wir planen das Meeting für nächste Woche.', 'We are planning the meeting for next week.'),
  make('organisieren', 'to organize', 'verb', 'B1', 'Ich organisiere die Konferenz.', 'I am organizing the conference.'),
  make('koordinieren', 'to coordinate', 'verb', 'B2', 'Wir müssen die Termine koordinieren.', 'We need to coordinate the schedules.'),
  make('vorbereiten', 'to prepare', 'verb', 'B1', 'Ich bereite die Präsentation vor.', 'I am preparing the presentation.'),
  make('präsentieren', 'to present', 'verb', 'B1', 'Ich präsentiere morgen die Zahlen.', 'I am presenting the numbers tomorrow.'),
  make('verhandeln', 'to negotiate', 'verb', 'B2', 'Wir verhandeln über den Preis.', 'We are negotiating the price.'),
  make('überzeugen', 'to convince', 'verb', 'B2', 'Ich muss den Kunden überzeugen.', 'I need to convince the customer.'),
  make('übernehmen', 'to take over', 'verb', 'B2', 'Sie übernimmt das neue Projekt.', 'She is taking over the new project.'),
  make('verantworten', 'to be responsible for', 'verb', 'B2', 'Er verantwortet das Marketing.', 'He is responsible for marketing.'),
  make('befördern', 'to promote', 'verb', 'B2', 'Der Chef will sie befördern.', 'The boss wants to promote her.'),
  make('einstellen', 'to hire', 'verb', 'B2', 'Wir stellen zwei neue Mitarbeiter ein.', 'We are hiring two new employees.'),
  make('kündigen', 'to resign / cancel', 'verb', 'B2', 'Er möchte seinen Job kündigen.', 'He wants to quit his job.'),
  make('zusammenarbeiten', 'to collaborate', 'verb', 'B2', 'Wir arbeiten eng zusammen.', 'We work closely together.'),
  // Email / correspondence phrases
  make('Sehr geehrte Frau', 'Dear Ms. (formal)', 'noun', 'B2', 'f', 'Sehr geehrte Frau Müller, ...', 'Dear Ms. Müller, ...'),
  make('Sehr geehrter Herr', 'Dear Mr. (formal)', 'noun', 'B2', 'm', 'Sehr geehrter Herr Schmidt, ...', 'Dear Mr. Schmidt, ...'),
  make('Mit freundlichen Grüßen', 'Sincerely', 'interj', 'B1', 'Mit freundlichen Grüßen, Anna', 'Sincerely, Anna'),
  make('die Anfrage', 'inquiry', 'noun', 'B1', 'f', 'Wir haben eine neue Anfrage.', 'We have a new inquiry.'),
  make('das Angebot', 'offer', 'noun', 'B1', 'n', 'Das Angebot ist günstig.', 'The offer is cheap.'),
  make('die Bestellung', 'order', 'noun', 'B1', 'f', 'Die Bestellung kommt morgen.', 'The order is coming tomorrow.'),
  make('die Rechnung', 'invoice', 'noun', 'B1', 'f', 'Bitte bezahlen Sie die Rechnung.', 'Please pay the invoice.'),
  make('die Quittung', 'receipt', 'noun', 'B1', 'f', 'Hier ist Ihre Quittung.', 'Here is your receipt.'),
  make('die Mahnung', 'dunning notice', 'noun', 'B2', 'f', 'Die Mahnung kam heute.', 'The dunning notice arrived today.'),
  make('die Zahlung', 'payment', 'noun', 'B1', 'f', 'Die Zahlung ist überfällig.', 'The payment is overdue.'),
  make('die Überweisung', 'transfer', 'noun', 'B1', 'f', 'Die Überweisung ist angekommen.', 'The transfer has arrived.'),
  make('der Betrag', 'amount', 'noun', 'B1', 'm', 'Der Betrag stimmt nicht.', 'The amount is wrong.'),
  make('die Summe', 'sum', 'noun', 'B1', 'f', 'Die Summe ist sehr hoch.', 'The sum is very high.'),
  make('die Steuer', 'tax', 'noun', 'B1', 'f', 'Die Steuer wird vom Gehalt abgezogen.', 'Tax is deducted from salary.'),
  make('die Mehrwertsteuer', 'VAT', 'noun', 'B2', 'f', 'Die Mehrwertsteuer beträgt 19%.', 'VAT is 19%.'),
  make('die Lohnsteuer', 'income tax', 'noun', 'B2', 'f', 'Die Lohnsteuer ist automatisch.', 'Income tax is automatic.'),
  // Meetings + projects
  make('der Termin', 'appointment', 'noun', 'B1', 'm', 'Der Termin ist um 14 Uhr.', 'The appointment is at 2 PM.'),
  make('der Zeitplan', 'schedule', 'noun', 'B1', 'm', 'Der Zeitplan ist eng.', 'The schedule is tight.'),
  make('der Arbeitsplan', 'work plan', 'noun', 'B2', 'm', 'Der Arbeitsplan steht.', 'The work plan is set.'),
  make('das Projekt', 'project', 'noun', 'A2', 'n', 'Das Projekt läuft gut.', 'The project is going well.'),
  make('die Aufgabe', 'task', 'noun', 'B1', 'f', 'Die Aufgabe ist nicht einfach.', 'The task is not easy.'),
  make('das Ziel', 'goal', 'noun', 'A2', 'n', 'Unser Ziel ist Wachstum.', 'Our goal is growth.'),
  make('die Deadline', 'deadline', 'noun', 'B1', 'f', 'Die Deadline ist morgen.', 'The deadline is tomorrow.'),
  make('der Bericht', 'report', 'noun', 'B1', 'm', 'Der Bericht ist fertig.', 'The report is finished.'),
  make('das Protokoll', 'minutes/protocol', 'noun', 'B2', 'n', 'Bitte schreibe das Protokoll.', 'Please write the minutes.'),
  make('die Tagesordnung', 'agenda', 'noun', 'B2', 'f', 'Die Tagesordnung ist lang.', 'The agenda is long.'),
  make('die Präsentation', 'presentation', 'noun', 'B1', 'f', 'Die Präsentation war gut.', 'The presentation was good.'),
  make('der Vortrag', 'talk/lecture', 'noun', 'B1', 'm', 'Der Vortrag beginnt um 9 Uhr.', 'The talk begins at 9 AM.'),
  make('die Diskussion', 'discussion', 'noun', 'B1', 'f', 'Die Diskussion war intensiv.', 'The discussion was intense.'),
  make('die Entscheidung', 'decision', 'noun', 'B1', 'f', 'Die Entscheidung ist schwer.', 'The decision is hard.'),
  make('der Vorschlag', 'proposal', 'noun', 'B1', 'm', 'Dein Vorschlag ist gut.', 'Your proposal is good.'),
  // Common phrases
  make('vereinbaren', 'to arrange/agree', 'verb', 'B1', 'Lass uns einen Termin vereinbaren.', 'Let us arrange a meeting.'),
  make('bestätigen', 'to confirm', 'verb', 'B1', 'Bitte bestätige den Termin.', 'Please confirm the appointment.'),
  make('verschieben', 'to postpone', 'verb', 'B2', 'Wir müssen das Meeting verschieben.', 'We need to postpone the meeting.'),
  make('absagen', 'to cancel', 'verb', 'B1', 'Er musste das Meeting absagen.', 'He had to cancel the meeting.'),
  make('zustimmen', 'to agree', 'verb', 'B1', 'Ich stimme dem Vorschlag zu.', 'I agree with the proposal.'),
  make('ablehnen', 'to decline', 'verb', 'B2', 'Wir müssen den Antrag ablehnen.', 'We have to decline the request.'),
  make('sich beschweren', 'to complain', 'verb', 'B2', 'Der Kunde möchte sich beschweren.', 'The customer wants to complain.'),
  make('sich entschuldigen', 'to apologize', 'verb', 'B2', 'Ich möchte mich entschuldigen.', 'I would like to apologize.'),
  make('sich bedanken', 'to thank', 'verb', 'B2', 'Ich möchte mich bei Ihnen bedanken.', 'I would like to thank you.'),
  make('erinnern an', 'to remind of', 'verb', 'B2', 'Bitte erinnere mich an den Termin.', 'Please remind me of the appointment.'),
  make('hinweisen auf', 'to point out', 'verb', 'B2', 'Ich muss auf das Problem hinweisen.', 'I have to point out the issue.'),
  // Job titles (common)
  make('der Manager', 'manager', 'noun', 'B1', 'm', 'Der Manager leitet das Team.', 'The manager leads the team.'),
  make('die Managerin', 'manager (f)', 'noun', 'B1', 'f', 'Die Managerin hat eine neue Strategie.', 'The manager (female) has a new strategy.'),
  make('der Direktor', 'director', 'noun', 'B2', 'm', 'Der Direktor kommt aus München.', 'The director is from Munich.'),
  make('die Direktorin', 'director (f)', 'noun', 'B2', 'f', 'Die Direktorin spricht auf der Konferenz.', 'The director (female) speaks at the conference.'),
  make('der Geschäftsführer', 'CEO/managing director', 'noun', 'B2', 'm', 'Der Geschäftsführer trifft eine Entscheidung.', 'The CEO makes a decision.'),
  make('der Vorstand', 'board/executive', 'noun', 'B2', 'm', 'Der Vorstand trifft sich heute.', 'The board meets today.'),
  make('der Angestellte', 'employee (formal)', 'noun', 'B2', 'm', 'Der Angestellte arbeitet seit 10 Jahren hier.', 'The employee has worked here for 10 years.'),
  make('der Auszubildende', 'trainee', 'noun', 'B2', 'm', 'Der Auszubildende lernt viel.', 'The trainee learns a lot.'),
  make('der Praktikant', 'intern', 'noun', 'B2', 'm', 'Der Praktikant hilft im Marketing.', 'The intern helps in marketing.'),
  make('der Freiberufler', 'freelancer', 'noun', 'B2', 'm', 'Der Freiberufler arbeitet von zu Hause.', 'The freelancer works from home.'),
  // Career vocabulary
  make('die Karriere', 'career', 'noun', 'B2', 'f', 'Ihre Karriere ist wichtig.', 'Her career is important.'),
  make('die Erfahrung', 'experience', 'noun', 'B1', 'f', 'Er hat viel Erfahrung.', 'He has a lot of experience.'),
  make('die Qualifikation', 'qualification', 'noun', 'B2', 'f', 'Die Qualifikation passt zur Stelle.', 'The qualification fits the position.'),
  make('die Fähigkeit', 'ability/skill', 'noun', 'B2', 'f', 'Das ist eine wichtige Fähigkeit.', 'That is an important ability.'),
  make('die Kenntnisse', 'knowledge/skills (pl)', 'noun', 'B2', 'f', 'Gute Englischkenntnisse sind nötig.', 'Good English knowledge is required.'),
  make('das Gehalt', 'salary', 'noun', 'B1', 'n', 'Das Gehalt ist gut.', 'The salary is good.'),
  make('der Lohn', 'wage', 'noun', 'B2', 'm', 'Der Lohn wird wöchentlich gezahlt.', 'The wage is paid weekly.'),
  make('die Beförderung', 'promotion', 'noun', 'B2', 'f', 'Die Beförderung kommt im Juli.', 'The promotion comes in July.'),
  make('die Kündigung', 'dismissal/notice', 'noun', 'B2', 'f', 'Die Kündigung ist schriftlich.', 'The notice is in writing.'),
  make('die Stelle', 'position', 'noun', 'B1', 'f', 'Die Stelle ist ausgeschrieben.', 'The position is advertised.'),
  make('die Stellenausschreibung', 'job ad', 'noun', 'B2', 'f', 'Die Stellenausschreibung ist online.', 'The job ad is online.'),
  make('die Bewerbung', 'application', 'noun', 'B1', 'f', 'Meine Bewerbung ist fertig.', 'My application is ready.'),
  make('der Lebenslauf', 'CV/resume', 'noun', 'B1', 'm', 'Bitte schick mir deinen Lebenslauf.', 'Please send me your resume.'),
  make('das Anschreiben', 'cover letter', 'noun', 'B2', 'n', 'Das Anschreiben ist zu kurz.', 'The cover letter is too short.'),
  make('das Vorstellungsgespräch', 'job interview', 'noun', 'B1', 'n', 'Das Vorstellungsgespräch war gut.', 'The job interview was good.'),
];